services:
  db:
    image: postgres:18
    restart: always
    ports:
      - "3010:5432"
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: postgres          
      POSTGRES_DB: recipes_db
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: